import 'package:sis/core/common_widgets/country/country_model.dart';

final List<CountryModel> countries = [
  CountryModel(name: 'Afghanistan', code: '+93', flag: '🇦🇫'),
  CountryModel(name: 'Albania', code: '+355', flag: '🇦🇱'),
  CountryModel(name: 'Algeria', code: '+213', flag: '🇩🇿'),
  CountryModel(name: 'Andorra', code: '+376', flag: '🇦🇩'),
  CountryModel(name: 'Angola', code: '+244', flag: '🇦🇴'),
  CountryModel(name: 'Argentina', code: '+54', flag: '🇦🇷'),
  CountryModel(name: 'Armenia', code: '+374', flag: '🇦🇲'),
  CountryModel(name: 'Australia', code: '+61', flag: '🇦🇺'),
  CountryModel(name: 'Austria', code: '+43', flag: '🇦🇹'),
  CountryModel(name: 'Azerbaijan', code: '+994', flag: '🇦🇿'),
  CountryModel(name: 'Bahamas', code: '+1', flag: '🇧🇸'),
  CountryModel(name: 'Bahrain', code: '+973', flag: '🇧🇭'),
  CountryModel(name: 'Bangladesh', code: '+880', flag: '🇧🇩'),
  CountryModel(name: 'Barbados', code: '+1', flag: '🇧🇧'),
  CountryModel(name: 'Belarus', code: '+375', flag: '🇧🇾'),
  CountryModel(name: 'Belgium', code: '+32', flag: '🇧🇪'),
  CountryModel(name: 'Belize', code: '+501', flag: '🇧🇿'),
  CountryModel(name: 'Benin', code: '+229', flag: '🇧🇯'),
  CountryModel(name: 'Bhutan', code: '+975', flag: '🇧🇹'),
  CountryModel(name: 'Bolivia', code: '+591', flag: '🇧🇴'),
  CountryModel(name: 'Bosnia and Herzegovina', code: '+387', flag: '🇧🇦'),
  CountryModel(name: 'Botswana', code: '+267', flag: '🇧🇼'),
  CountryModel(name: 'Brazil', code: '+55', flag: '🇧🇷'),
  CountryModel(name: 'Brunei', code: '+673', flag: '🇧🇳'),
  CountryModel(name: 'Bulgaria', code: '+359', flag: '🇧🇬'),
  CountryModel(name: 'Burkina Faso', code: '+226', flag: '🇧🇫'),
  CountryModel(name: 'Burundi', code: '+257', flag: '🇧🇮'),
  CountryModel(name: 'Cambodia', code: '+855', flag: '🇰🇭'),
  CountryModel(name: 'Cameroon', code: '+237', flag: '🇨🇲'),
  CountryModel(name: 'Canada', code: '+1', flag: '🇨🇦'),
  CountryModel(name: 'Cape Verde', code: '+238', flag: '🇨🇻'),
  CountryModel(name: 'Central African Republic', code: '+236', flag: '🇨🇫'),
  CountryModel(name: 'Chad', code: '+235', flag: '🇹🇩'),
  CountryModel(name: 'Chile', code: '+56', flag: '🇨🇱'),
  CountryModel(name: 'China', code: '+86', flag: '🇨🇳'),
  CountryModel(name: 'Colombia', code: '+57', flag: '🇨🇴'),
  CountryModel(name: 'Comoros', code: '+269', flag: '🇰🇲'),
  CountryModel(name: 'Congo', code: '+242', flag: '🇨🇬'),
  CountryModel(
      name: 'Congo, Democratic Republic of the', code: '+243', flag: '🇨🇩'),
  CountryModel(name: 'Costa Rica', code: '+506', flag: '🇨🇷'),
  CountryModel(name: 'Croatia', code: '+385', flag: '🇭🇷'),
  CountryModel(name: 'Cuba', code: '+53', flag: '🇨🇺'),
  CountryModel(name: 'Cyprus', code: '+357', flag: '🇨🇾'),
  CountryModel(name: 'Czech Republic', code: '+420', flag: '🇨🇿'),
  CountryModel(name: 'Denmark', code: '+45', flag: '🇩🇰'),
  CountryModel(name: 'Djibouti', code: '+253', flag: '🇩🇯'),
  CountryModel(name: 'Dominica', code: '+1', flag: '🇩🇲'),
  CountryModel(name: 'Dominican Republic', code: '+1', flag: '🇩🇴'),
  CountryModel(name: 'Ecuador', code: '+593', flag: '🇪🇨'),
  CountryModel(name: 'Egypt', code: '+20', flag: '🇪🇬'),
  CountryModel(name: 'El Salvador', code: '+503', flag: '🇸🇻'),
  CountryModel(name: 'Equatorial Guinea', code: '+240', flag: '🇬🇶'),
  CountryModel(name: 'Eritrea', code: '+291', flag: '🇪🇷'),
  CountryModel(name: 'Estonia', code: '+372', flag: '🇪🇪'),
  CountryModel(name: 'Eswatini', code: '+268', flag: '🇸🇿'),
  CountryModel(name: 'Ethiopia', code: '+251', flag: '🇪🇹'),
  CountryModel(name: 'Fiji', code: '+679', flag: '🇫🇯'),
  CountryModel(name: 'Finland', code: '+358', flag: '🇫🇮'),
  CountryModel(name: 'France', code: '+33', flag: '🇫🇷'),
  CountryModel(name: 'Gabon', code: '+241', flag: '🇬🇦'),
  CountryModel(name: 'Gambia', code: '+220', flag: '🇬🇲'),
  CountryModel(name: 'Georgia', code: '+995', flag: '🇬🇪'),
  CountryModel(name: 'Germany', code: '+49', flag: '🇩🇪'),
  CountryModel(name: 'Ghana', code: '+233', flag: '🇬🇭'),
  CountryModel(name: 'Greece', code: '+30', flag: '🇬🇷'),
  CountryModel(name: 'Grenada', code: '+1', flag: '🇬🇩'),
  CountryModel(name: 'Guatemala', code: '+502', flag: '🇬🇹'),
  CountryModel(name: 'Guinea', code: '+224', flag: '🇬🇳'),
  CountryModel(name: 'Guinea-Bissau', code: '+245', flag: '🇬🇼'),
  CountryModel(name: 'Guyana', code: '+592', flag: '🇬🇾'),
  CountryModel(name: 'Haiti', code: '+509', flag: '🇭🇹'),
  CountryModel(name: 'Honduras', code: '+504', flag: '🇭🇳'),
  CountryModel(name: 'Hungary', code: '+36', flag: '🇭🇺'),
  CountryModel(name: 'Iceland', code: '+354', flag: '🇮🇸'),
  CountryModel(name: 'India', code: '+91', flag: '🇮🇳'),
  CountryModel(name: 'Indonesia', code: '+62', flag: '🇮🇩'),
  CountryModel(name: 'Iran', code: '+98', flag: '🇮🇷'),
  CountryModel(name: 'Iraq', code: '+964', flag: '🇮🇶'),
  CountryModel(name: 'Ireland', code: '+353', flag: '🇮🇪'),
  CountryModel(name: 'Israel', code: '+972', flag: '🇮🇱'),
  CountryModel(name: 'Italy', code: '+39', flag: '🇮🇹'),
  CountryModel(name: 'Jamaica', code: '+1', flag: '🇯🇲'),
  CountryModel(name: 'Japan', code: '+81', flag: '🇯🇵'),
  CountryModel(name: 'Jordan', code: '+962', flag: '🇯🇴'),
  CountryModel(name: 'Kazakhstan', code: '+7', flag: '🇰🇿'),
  CountryModel(name: 'Kenya', code: '+254', flag: '🇰🇪'),
  CountryModel(name: 'Kiribati', code: '+686', flag: '🇰🇮'),
  CountryModel(name: 'Kuwait', code: '+965', flag: '🇰🇼'),
  CountryModel(name: 'Kyrgyzstan', code: '+996', flag: '🇰🇬'),
  CountryModel(name: 'Laos', code: '+856', flag: '🇱🇦'),
  CountryModel(name: 'Latvia', code: '+371', flag: '🇱🇻'),
  CountryModel(name: 'Lebanon', code: '+961', flag: '🇱🇧'),
  CountryModel(name: 'Lesotho', code: '+266', flag: '🇱🇸'),
  CountryModel(name: 'Liberia', code: '+231', flag: '🇱🇷'),
  CountryModel(name: 'Libya', code: '+218', flag: '🇱🇾'),
  CountryModel(name: 'Liechtenstein', code: '+423', flag: '🇱🇮'),
  CountryModel(name: 'Lithuania', code: '+370', flag: '🇱🇹'),
  CountryModel(name: 'Luxembourg', code: '+352', flag: '🇱🇺'),
  CountryModel(name: 'Madagascar', code: '+261', flag: '🇲🇬'),
  CountryModel(name: 'Malawi', code: '+265', flag: '🇲🇼'),
  CountryModel(name: 'Malaysia', code: '+60', flag: '🇲🇾'),
  CountryModel(name: 'Maldives', code: '+960', flag: '🇲🇻'),
  CountryModel(name: 'Mali', code: '+223', flag: '🇲🇱'),
  CountryModel(name: 'Malta', code: '+356', flag: '🇲🇹'),
  CountryModel(name: 'Marshall Islands', code: '+692', flag: '🇲🇭'),
  CountryModel(name: 'Mauritania', code: '+222', flag: '🇲🇷'),
  CountryModel(name: 'Mauritius', code: '+230', flag: '🇲🇺'),
  CountryModel(name: 'Mexico', code: '+52', flag: '🇲🇽'),
  CountryModel(name: 'Micronesia', code: '+691', flag: '🇫🇲'),
  CountryModel(name: 'Moldova', code: '+373', flag: '🇲🇩'),
  CountryModel(name: 'Monaco', code: '+377', flag: '🇲🇨'),
  CountryModel(name: 'Mongolia', code: '+976', flag: '🇲🇳'),
  CountryModel(name: 'Montenegro', code: '+382', flag: '🇲🇪'),
  CountryModel(name: 'Morocco', code: '+212', flag: '🇲🇦'),
  CountryModel(name: 'Mozambique', code: '+258', flag: '🇲🇿'),
  CountryModel(name: 'Myanmar', code: '+95', flag: '🇲🇲'),
  CountryModel(name: 'Namibia', code: '+264', flag: '🇳🇦'),
  CountryModel(name: 'Nauru', code: '+674', flag: '🇳🇷'),
  CountryModel(name: 'Nepal', code: '+977', flag: '🇳🇵'),
  CountryModel(name: 'Netherlands', code: '+31', flag: '🇳🇱'),
  CountryModel(name: 'New Zealand', code: '+64', flag: '🇳🇿'),
  CountryModel(name: 'Nicaragua', code: '+505', flag: '🇳🇮'),
  CountryModel(name: 'Niger', code: '+227', flag: '🇳🇪'),
  CountryModel(name: 'Nigeria', code: '+234', flag: '🇳🇬'),
  CountryModel(name: 'North Korea', code: '+850', flag: '🇰🇵'),
  CountryModel(name: 'North Macedonia', code: '+389', flag: '🇲🇰'),
  CountryModel(name: 'Norway', code: '+47', flag: '🇳🇴'),
  CountryModel(name: 'Oman', code: '+968', flag: '🇴🇲'),
  CountryModel(name: 'Pakistan', code: '+92', flag: '🇵🇰'),
  CountryModel(name: 'Palau', code: '+680', flag: '🇵🇼'),
  CountryModel(name: 'Panama', code: '+507', flag: '🇵🇦'),
  CountryModel(name: 'Papua New Guinea', code: '+675', flag: '🇵🇬'),
  CountryModel(name: 'Paraguay', code: '+595', flag: '🇵🇾'),
  CountryModel(name: 'Peru', code: '+51', flag: '🇵🇪'),
  CountryModel(name: 'Philippines', code: '+63', flag: '🇵🇭'),
  CountryModel(name: 'Poland', code: '+48', flag: '🇵🇱'),
  CountryModel(name: 'Portugal', code: '+351', flag: '🇵🇹'),
  CountryModel(name: 'Qatar', code: '+974', flag: '🇶🇦'),
  CountryModel(name: 'Romania', code: '+40', flag: '🇷🇴'),
  CountryModel(name: 'Russia', code: '+7', flag: '🇷🇺'),
  CountryModel(name: 'Rwanda', code: '+250', flag: '🇷🇼'),
  CountryModel(name: 'Saint Kitts and Nevis', code: '+1', flag: '🇰🇳'),
  CountryModel(name: 'Saint Lucia', code: '+1', flag: '🇱🇨'),
  CountryModel(
      name: 'Saint Vincent and the Grenadines', code: '+1', flag: '🇻🇨'),
  CountryModel(name: 'Samoa', code: '+685', flag: '🇼🇸'),
  CountryModel(name: 'San Marino', code: '+378', flag: '🇸🇲'),
  CountryModel(name: 'Sao Tome and Principe', code: '+239', flag: '🇸🇹'),
  CountryModel(name: 'Saudi Arabia', code: '+966', flag: '🇸🇦'),
  CountryModel(name: 'Senegal', code: '+221', flag: '🇸🇳'),
  CountryModel(name: 'Serbia', code: '+381', flag: '🇷🇸'),
  CountryModel(name: 'Seychelles', code: '+248', flag: '🇸🇨'),
  CountryModel(name: 'Sierra Leone', code: '+232', flag: '🇸🇱'),
  CountryModel(name: 'Singapore', code: '+65', flag: '🇸🇬'),
  CountryModel(name: 'Slovakia', code: '+421', flag: '🇸🇰'),
  CountryModel(name: 'Slovenia', code: '+386', flag: '🇸🇮'),
  CountryModel(name: 'Solomon Islands', code: '+677', flag: '🇸🇧'),
  CountryModel(name: 'Somalia', code: '+252', flag: '🇸🇴'),
  CountryModel(name: 'South Africa', code: '+27', flag: '🇿🇦'),
  CountryModel(name: 'South Korea', code: '+82', flag: '🇰🇷'),
  CountryModel(name: 'South Sudan', code: '+211', flag: '🇸🇸'),
  CountryModel(name: 'Spain', code: '+34', flag: '🇪🇸'),
  CountryModel(name: 'Sri Lanka', code: '+94', flag: '🇱🇰'),
  CountryModel(name: 'Sudan', code: '+249', flag: '🇸🇩'),
  CountryModel(name: 'Suriname', code: '+597', flag: '🇸🇷'),
  CountryModel(name: 'Sweden', code: '+46', flag: '🇸🇪'),
  CountryModel(name: 'Switzerland', code: '+41', flag: '🇨🇭'),
  CountryModel(name: 'Syria', code: '+963', flag: '🇸🇾'),
  CountryModel(name: 'Taiwan', code: '+886', flag: '🇹🇼'),
  CountryModel(name: 'Tajikistan', code: '+992', flag: '🇹🇯'),
  CountryModel(name: 'Tanzania', code: '+255', flag: '🇹🇿'),
  CountryModel(name: 'Thailand', code: '+66', flag: '🇹🇭'),
  CountryModel(name: 'Togo', code: '+228', flag: '🇹🇬'),
  CountryModel(name: 'Tonga', code: '+676', flag: '🇹🇴'),
  CountryModel(name: 'Trinidad and Tobago', code: '+1', flag: '🇹🇹'),
  CountryModel(name: 'Tunisia', code: '+216', flag: '🇹🇳'),
  CountryModel(name: 'Turkey', code: '+90', flag: '🇹🇷'),
  CountryModel(name: 'Turkmenistan', code: '+993', flag: '🇹🇲'),
  CountryModel(name: 'Tuvalu', code: '+688', flag: '🇹🇻'),
  CountryModel(name: 'Uganda', code: '+256', flag: '🇺🇬'),
  CountryModel(name: 'Ukraine', code: '+380', flag: '🇺🇦'),
  CountryModel(name: 'United Arab Emirates', code: '+971', flag: '🇦🇪'),
  CountryModel(name: 'United Kingdom', code: '+44', flag: '🇬🇧'),
  CountryModel(name: 'United States', code: '+1', flag: '🇺🇸'),
  CountryModel(name: 'Uruguay', code: '+598', flag: '🇺🇾'),
  CountryModel(name: 'Uzbekistan', code: '+998', flag: '🇺🇿'),
  CountryModel(name: 'Vanuatu', code: '+678', flag: '🇻🇺'),
  CountryModel(name: 'Vatican City', code: '+379', flag: '🇻🇦'),
  CountryModel(name: 'Venezuela', code: '+58', flag: '🇻🇪'),
  CountryModel(name: 'Vietnam', code: '+84', flag: '🇻🇳'),
  CountryModel(name: 'Yemen', code: '+967', flag: '🇾🇪'),
  CountryModel(name: 'Zambia', code: '+260', flag: '🇿🇲'),
  CountryModel(name: 'Zimbabwe', code: '+263', flag: '🇿🇼'),
];
