// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: "AIzaSyBSR_gDitl3k-h1eajL37a_ddvjCQHbjMw",
//     authDomain: "tmg-sis.firebaseapp.com",
//     projectId: "tmg-sis",
//     storageBucket: "tmg-sis.appspot.com",
//     messagingSenderId: "213566736306",
//     appId: "1:213566736306:web:7978a67a80ec1e39c086ab",
//     measurementId: "G-8QJ3LXBFP4",
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: "AIzaSyBSR_gDitl3k-h1eajL37a_ddvjCQHbjMw",
//     appId: "1:213566736306:web:7978a67a80ec1e39c086ab",
//     messagingSenderId: '213493351365',
//     projectId: "tmg-sis",
//     storageBucket: "tmg-sis.appspot.com",
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: "AIzaSyBSR_gDitl3k-h1eajL37a_ddvjCQHbjMw",
//     appId: "1:213566736306:android:a9a4c332cc849ba0c086ab",
//     messagingSenderId: '213493351365',
//     projectId: "tmg-sis",
//     storageBucket: "tmg-sis.appspot.com",
//     iosClientId:
//         '213493351365-jn1r1ifhlcd3q94thr354tns05f8h79q.apps.googleusercontent.com',
//     iosBundleId: 'com.example.synergy',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: "AIzaSyBSR_gDitl3k-h1eajL37a_ddvjCQHbjMw",
//     appId: "1:213566736306:web:7978a67a80ec1e39c086ab",
//     messagingSenderId: '213493351365',
//     projectId: "tmg-sis",
//     storageBucket: "tmg-sis.appspot.com",
//     iosClientId:
//         '213493351365-jn1r1ifhlcd3q94thr354tns05f8h79q.apps.googleusercontent.com',
//     iosBundleId: 'com.example.synergy',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: "AIzaSyBSR_gDitl3k-h1eajL37a_ddvjCQHbjMw",
//     appId: "1:213566736306:web:7978a67a80ec1e39c086ab",
//     messagingSenderId: '213493351365',
//     projectId: "tmg-sis",
//     authDomain: 'synergy-4b602.firebaseapp.com',
//     storageBucket: "tmg-sis.appspot.com",
//     measurementId: 'G-6F8ZSN21ED',
//   );
// }
